version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
hooks:
  BeforeInstall:
    - location: config/script/install_dependencies
      timeout: 300
      runas: root
    - location: config/script/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: config/script/stop_server
      timeout: 300
      runas: root

